# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 883463338978.dkr.ecr.eu-west-2.amazonaws.com/klipbored-backend:latest
        ports:
        - containerPort: 5000
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  selector:
    app: backend  # Ensure this label matches your backend pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # backend container listener port
  type: ClusterIP
