# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default  # Make sure this matches your Fargate profile namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 883463338978.dkr.ecr.eu-west-2.amazonaws.com/klipbored-frontend:latest
        ports:
        - containerPort: 80
        env:
          - name: BACKEND_SERVICE_URL
            value: "http://backend-service"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend  # This should match the labels on your application pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # The type can be ClusterIP as the ALB will handle external access
