name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:

  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Caching builds
      - name: Cache Docker layers for Frontend
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('klipbored-frontend/Dockerfile', 'klipbored-frontend/**') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-buildx-
  
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.FRONTEND_REPO }}:latest ./klipbored-frontend
          docker push ${{ secrets.FRONTEND_REPO }}:latest

      # Caching builds
      - name: Cache Docker layers for Backend
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('klipbored-backend/Dockerfile', 'klipbored-backend/**') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.BACKEND_REPO }}:latest ./klipbored-backend
          docker push ${{ secrets.BACKEND_REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_push]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy Frontend to EKS
        run: |
          kubectl apply -f ./k8s/frontend-deployment.yaml

      - name: Deploy Backend to EKS
        run: |
          kubectl apply -f ./k8s/backend-deployment.yaml
