name: ECR Login

on:
  workflow_call:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        type: string

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.region }}
